<#
.SYNOPSIS
    Intune detection for the HBK_1F_PR2 direct TCP/IP printer.

.DESCRIPTION
    Upload this file as the Win32 app's custom detection script (it is NOT read from the
    package, so values are hardcoded). Runs as SYSTEM, which can see machine-wide local
    printers. Detected only when the printer exists AND uses the expected driver AND its
    port points at the expected DDNS hostname - so a stale/misconfigured printer triggers
    a repair install.
    Exit 0 + stdout = detected; exit 1 = not detected.

.NOTES
    Author:  Oji (cmcleod1@umd.edu)
    Date:    2026-09-22
    Version: 1.0.0
    Generated by _Build\Build-StaffPrinterFolders.ps1 - edit the master CSV, not this file.
#>
$PrinterName = 'HBK_1F_PR2'
$DriverName  = 'Canon Generic Plus UFR II'
$HostAddress = 'HBK_1F_PR2.resource.dyn.umd.edu'
$PortName    = "IP_$HostAddress"

try {
    $printer = Get-Printer -Name $PrinterName -ErrorAction Stop
    $port    = Get-PrinterPort -Name $printer.PortName -ErrorAction Stop

    if ($printer.DriverName -eq $DriverName -and
        $printer.PortName -eq $PortName -and
        $port.PrinterHostAddress -eq $HostAddress) {
        Write-Output "DETECTED: $PrinterName -> $HostAddress ($DriverName)"
        exit 0
    }
    exit 1
} catch {
    exit 1
}

