<#
.SYNOPSIS
    Compares two previously saved registry snapshots
    
.DESCRIPTION
    Load and compare two .xml snapshot files generated by Compare-RegistryChanges.ps1
    
.EXAMPLE
    .\Compare-SavedSnapshots.ps1 -BeforeFile "Snapshot_Before.xml" -AfterFile "Snapshot_After.xml"
#>

param(
    [Parameter(Mandatory)]
    [string]$BeforeFile,
    
    [Parameter(Mandatory)]
    [string]$AfterFile,
    
    [Parameter()]
    [string]$OutputFolder = (Join-Path $env:USERPROFILE "Desktop\RegistryAnalysis")
)

if (-not (Test-Path $BeforeFile)) {
    Write-Host "Before snapshot not found: $BeforeFile" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path $AfterFile)) {
    Write-Host "After snapshot not found: $AfterFile" -ForegroundColor Red
    exit 1
}

Write-Host "Loading snapshots..." -ForegroundColor Cyan
$beforeSnapshot = Import-Clixml -Path $BeforeFile
$afterSnapshot = Import-Clixml -Path $AfterFile

Write-Host "Before: $($beforeSnapshot.Timestamp)" -ForegroundColor Gray
Write-Host "After:  $($afterSnapshot.Timestamp)" -ForegroundColor Gray
Write-Host ""

# Use the same comparison logic from main script
# ... (include Compare-RegistrySnapshots and Export-ChangesReport functions here)

$changes = Compare-RegistrySnapshots -Before $beforeSnapshot -After $afterSnapshot
Export-ChangesReport -Changes $changes -OutputPath $OutputFolder

Write-Host ""
Write-Host "Comparison complete!" -ForegroundColor Green